# .upptimerc.yml

owner: kubeara
repo: status

sites:
  - name: Kubeara API
    url: https://api.kubeara.dev/api/health
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Kubeara Dashboard
    url: https://app.kubeara.dev
    expectedStatusCodes:
      - 200

  - name: Kubeara Website
    url: https://kubeara.dev
    expectedStatusCodes:
      - 200

notifications:
  - type: slack
    webhook-url: $GOOGLE_CHAT_WEBHOOK

status-website:
  name: Kubeara Status
  cname: status.kubeara.dev